### ISSUE TITLE
Todo: Serving static/dynamic contents with CloudFront CDN

### ISSUE THREAD

**Issue by haeramkeem** [k-hackathon2022/Elon-kiosk-config#11]
### S3

- [x] Integrate two S3 buckets

### CloudFront

- [x] Link S3 bucket to the CloudFront
- [x] Path load balancing (`/customer`, `/business`, `/api`)
- [x] Create CloudFront distribution
